apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-controller-manager
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      initContainers:
        - name: p1as-oauth
          image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/p14c-integration:pdo-9860-osd-rolemapping

