apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: os-controller-manager
      namespace: elastic-stack-logging
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/name=p1as-oauth/image
        value: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration:1.19.2-role-query-patch
