apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: opensearch-securityconfig
    namespace: elastic-stack-logging
    behavior: replace
    type: Opaque
    files:
      - action_groups.yml
      - allowlist.yml
      - audit.yml
      - nodes_dn.yml
      - roles.yml
      - tenants.yml

generatorOptions:
  disableNameSuffixHash: true
