apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-configuration
        namespace: ingress-nginx-public
      data:
        main-snippet: load_module /usr/lib/nginx/modules/ngx_http_sigsci_module.so;
        worker-processes: '4'
        max-worker-connections: '0'
        log-format-upstream: '$remote_addr $host $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
