apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: elastic-stack-logging

components:
- logstash/base
- hipaa/fluentbit
- hipaa/logstash
- lake/fluentbit
- lake/logstash
- logstash/both
