apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: logstash-elastic
      spec:
        template:
          spec:
            serviceAccountName: logstash-elastic
            containers:
              - name: logstash
                resources:
                  limits:
                    memory: 14Gi
                    cpu: "4"
                  requests:
                    memory: 12Gi
                    cpu: "4"
                env:
                  - name: PIPELINE_BATCH_SIZE
                    value: '5000'
                  - name: PIPELINE_WORKERS
                    value: "16"
                  - name: LS_JAVA_OPTS
                    value: '-Xms8g -Xmx8g -XX:MaxDirectMemorySize=2g'
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: logstash-elastic
        namespace: elastic-stack-logging
      spec:
        minReplicas: 6
        maxReplicas: 7