apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:3.2.1
        
        # -------------------------------------------------
        # 1. FIX: Explicitly remove the old httpGet handler
        # -------------------------------------------------
        livenessProbe:
          httpGet: null  # This removes the existing httpGet handler
          exec:
            command:
              - /bin/sh
              - -c
              - pgrep fluent-bit >/dev/null
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          # This replaces the entire readiness probe with the v3.2.1 API check
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 10
          periodSeconds: 10

        # -------------------------------------------------
        # 2. FIX: Explicitly delete the orphaned mounts
        # -------------------------------------------------
        volumeMounts:
        - name: fluent-bit-pipeline-s3
          $patch: delete
        - name: fluent-bit-pipeline-customer
          $patch: delete
        # Ensure the state directory is correctly mounted
        - name: fluentbitstate
          mountPath: /fluent-bit/state

      volumes:
      # These delete the actual storage definitions
      - name: fluent-bit-pipeline-s3
        $patch: delete
      - name: fluent-bit-pipeline-customer
        $patch: delete
      
      # Correctly define the hostPath for the 4GB buffer
      - name: fluentbitstate
        hostPath:
          path: /fluent-bit/state
          type: DirectoryOrCreate
