apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/amazon/aws-for-fluent-bit:2.31.7

        command:
          - /bin/sh
        args:
          - '-c'
          - 'S3_BUCKET_NAME=${S3_BUCKET#s3://} /entrypoint.sh'

        env:
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: s3-raw-logs-bucket
                key: bucketName
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: cluster-info
                key: logs.region

        volumeMounts:
          - name: fluent-bit-pipeline-s3
            $patch: delete
          - name: fluent-bit-pipeline-customer
            $patch: delete

      volumes:
        - name: fluent-bit-pipeline-s3
          $patch: delete
        - name: fluent-bit-pipeline-customer
          $patch: delete
