apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: fluentbit-pipeline-elk-patch.yaml
    target:
      kind: ConfigMap
      name: fluent-bit-pipeline-elk
      labelSelector: k8s-app=fluent-bit

patchesStrategicMerge:
  - fluentbit-config-patch.yaml
  - fluentbit-patch.yaml