apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: pingaccess-was
        namespace: ping-cloud
      spec:
        minReplicas: 2
        maxReplicas: 5