apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# This patch applies to P1AS <= 2.3.x - ensures that argocd-repo-server always pulls the repo install-custom-tools container

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
        namespace: argocd
      spec:
        template:
          spec:
            initContainers:
              - name: install-custom-tools
                imagePullPolicy: Always