# =============================================================================
# pipeline-hipaa-outputs.conf
# HIPAA-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.hipaa.general.*
    Host                logstash-elasic-compliance
    Port                8086
    storage.total_limit_size  250M
    storage.max_chunks_up     4
    storage.backlog.mem_limit 10M
    Retry_Limit         300
    ensure_delivery     false
    workers             1
