# =============================================================================
# pipeline-hipaa-outputs.conf
# HIPAA-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.hipaa.general.*
    Host                logstash-elastic-compliance
    Port                8086
    Retry_Limit         300
    workers             1
