apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit/fluentbit-resources.yaml
- path: elastic-stack/logstash/logstash.yaml
- path: elastic-stack/logstash/logstash-s3.yaml
- path: elastic-stack/logstash/hpa.yaml
- path: elastic-stack/logstash/storage.yaml
- path: elastic-stack/opensearch/cluster.yaml

configMapGenerator:
- behavior: replace
  name: fluent-bit-config
  files:
  - fluentbit/configs/fluent-bit.conf
- behavior: replace
  name: fluent-bit-pipeline-core
  files:
  - fluentbit/configs/pipeline-core.conf
- behavior: replace
  name: fluent-bit-pipeline-outputs
  files:
  - fluentbit/configs/pipeline-outputs.conf
