apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# v2.2.1 patch to remove modsecurity annotations from PA-WAS ingresses
# since we removed modsecurity from nginx after updating ingress-nginx to 1.14.4
patches:
  - patch: |-
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1enable-modsecurity
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1modsecurity-snippet
    target:
      kind: Ingress
      annotationSelector: "nginx.ingress.kubernetes.io/enable-modsecurity"
