apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic-compliance
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: logstash
        readinessProbe:
          httpGet:
            port: 8085
        startupProbe:
          httpGet:
            port: 8085
        ports:
        - containerPort: 8085
          name: http-lake-in
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-elastic-compliance
  namespace: elastic-stack-logging
spec:
  ports:
  - port: 9600
    name: rest
  - port: 9198
    name: metrics
  - port: 8085
    name: http-lake-in
