apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit-resources.yaml

configMapGenerator:
- behavior: replace
  name: fluent-bit-config
  files:
  - configs/fluent-bit.conf
- behavior: replace
  name: fluent-bit-pipeline-core
  files:
  - configs/pipeline-core.conf
- behavior: replace
  name: fluent-bit-pipeline-outputs
  files:
  - configs/pipeline-outputs.conf
