apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: logstash-compliance-pdb
  namespace: elastic-stack-logging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: logstash-elastic-compliance
