apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: mounts-patch.yaml

configMapGenerator:
- name: logstash-pipeline-datalake-compliance
  namespace: elastic-stack-logging
  files:
  - configs/datalake.conf
- name: logstash-pipeline-fragment-datalake-compliance
  namespace: elastic-stack-logging
  files:
  - configs/10-datalake.yml
