apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: fluent-bit
        namespace: elastic-stack-logging
      spec:
        template:
          spec:
            containers:
            - name: fluent-bit
              resources:
                limits:
                  memory: 4Gi
                  cpu: "2"
                requests:
                  memory: 4Gi
                  cpu: "2"