apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-controller-manager
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      initContainers:
        - name: p1as-oauth
          image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration:v2.0.2-RC1
