# =============================================================================
# pipeline-lake-outputs.conf
# Lake-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.lake.general.*
    Host                logstash-elasic-compliance
    Port                8085
    storage.total_limit_size  500M
    storage.max_chunks_up     8
    storage.backlog.mem_limit 20M
    Retry_Limit         300
    ensure_delivery     false
    workers             1
