# =============================================================================
# pipeline-lake-outputs.conf
# Lake-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.lake.general.*
    Host                logstash-elastic-compliance
    Port                8085
    Retry_Limit         300
    workers             1
