apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  nodePools:
    - component: hot
      labels:
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch-cluster-hot
      replicas: 3
      diskSize: "50Gi"
      jvm: -Xmx3000M -Xms3000M
      pdb:
        enable: true
        maxUnavailable: 1
      additionalConfig:
        node.attr.temp: "hot"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchExpressions:
                    - key: opster.io/opensearch-nodepool
                      operator: In
                      values:
                        - hot
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: opster.io/opensearch-nodepool
                    operator: In
                    values:
                      - hot
              topologyKey: kubernetes.io/hostname
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
            - "ReadWriteOnce"
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 4Gi
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
        - "remote_cluster_client"
        - "search"
