# =============================================================================
# fluent-bit.conf — Tier 2 
# Ref: https://pingidentity.atlassian.net/wiki/spaces/PDA/pages/2712305794/FluentBit+Pipeline+Configuration
# =============================================================================

[SERVICE]
    Log_Level    ${FLB_LOG_LEVEL}
    Flush                     10
    Daemon                    off
    Parsers_File              parsers.conf
    storage.path              /fluent-bit/state/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 256M
    storage.max_chunks_up     1024
    storage.metrics           on
    scheduler.base            15
    scheduler.cap             300
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    Health_Check On

@INCLUDE /fluent-bit/etc/pipeline-*.conf
